import type { Metadata } from "next";
import PrivateProvider from "@/providers/PrivateProvider";
import { getIsAuth } from "@/utils";
import {redirect} from "next/navigation";
import styles from "@/app/page.module.css";
import AsideChats from "@/components/AsideChats/AsideChats";
import {cookies} from "next/headers";
import {deleteUserCookies} from "@/app/actions";
import PotentialChats from "@/components/PotintialChats/PotentialChats";
import PotentialChatsServer from "@/components/PotintialChats/PotentialChatsServer";
import NewsServer from "@/components/News/News.server";
export const metadata: Metadata = {
    title: "Auth",
    description: "Generated by create next app",
};

export default async function PrivateLayout({children}: Readonly<{ children: React.ReactNode }>) {
    // return (
    //     <PrivateProvider>
    //         {children}
    //     </PrivateProvider>
    // )

    // const isAuth = await getIsAuth()
    // console.log('isAuth', isAuth)
    // if (!isAuth) {
    //     return redirect('/login')
    // }
    // if (isAuth?.serverError)
    //     return <main className={styles.mainWrapper}>
    //         Server error
    //     </main>

    return (
        <main className={styles.mainWrapper}>
            <AsideChats/>
            {children}
            <NewsServer/>
        </main>
    )
}
