import type { Metadata } from "next";
import PrivateProvider from "@/providers/PrivateProvider";
import { getIsAuth } from "@/utils";
import {redirect} from "next/navigation";
import styles from "@/app/page.module.css";
import AsideChats from "@/components/AsideChats/AsideChats";
import {cookies} from "next/headers";
import {deleteUserCookies} from "@/app/actions";
import PotentialChats from "@/components/PotintialChats/PotentialChats";
import PotentialChatsServer from "@/components/PotintialChats/PotentialChatsServer";
export const metadata: Metadata = {
    title: "Auth",
    description: "Generated by create next app",
};

export default async function PrivateLayout({children}: Readonly<{ children: React.ReactNode }>) {
    // return (
    //     <PrivateProvider>
    //         {children}
    //     </PrivateProvider>
    // )

    const isAuth = await getIsAuth()

    if (!isAuth) {
        return redirect('/login')
    }

    return (
        <main className={styles.mainWrapper}>
            <AsideChats/>
            {children}
            <PotentialChatsServer/>
        </main>
    )
}
