import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css'
import "./reset.css";
import Header from "@/components/Header/Header";
import MainProvider from "@/providers/index";
import {getIsAuth, getUserChats, getUserFromCookies} from "@/utils";
import {store} from "@/store/store";
import {setChats} from "@/store/slices/chatSlice";
import {redirect} from "next/navigation";

const inter = Montserrat({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    // const userChats = await getUserChats()
    // store.dispatch(setChats(userChats))
    // console.log('store: ', store.getState())

    return (
        <html>
            <body className={inter.className}>
                <MainProvider>
                    <Header/>
                    {children}
                </MainProvider>
            </body>
        </html>
    )
}
