import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css'
import "./reset.css";
import Header from "@/components/Header/Header";
import MainProvider from "@/providers/index";
import {ToastContainer} from "react-toastify";
import styles from "@/app/page.module.css";

const inter = Montserrat({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {

    return (
        <html>
            <body className={inter.className}>
                <MainProvider>
                    <ToastContainer/>
                    <Header/>
                    <main className={styles.mainWrapper}>
                        {children}
                    </main>
                </MainProvider>
            </body>
        </html>
    )
}
