import type {Metadata} from "next";
import PublicProvider from "@/providers/PublicProvider";
import {getIsAuth} from "../../utils";
import {redirect} from "next/navigation";

export const metadata: Metadata = {
    title: "Auth",
    description: "Generated by create next app",
};

export default async function PublicLayout({children}: Readonly<{ children: React.ReactNode }>) {
    // return (
    //     <PublicProvider>
    //         {children}
    //     </PublicProvider>
    // // )
    // const isAuth = await getIsAuth()
    // if (isAuth) redirect('/')
    return <>{children}</>
}
